# fly.toml app configuration file generated for playtaipan on 2026-07-11T20:53:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playtaipan'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'saves'
  destination = '/app/saves'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
