"""Taipan! web server: serves the retro UI and drives game sessions.

Persistence design: the engine is deterministic given its RNG seed, so a
game is fully described by (seed, list of inputs). Every step appends to
an on-disk event log in saves/; an unknown session id is restored by
replaying its log into a fresh generator. This survives server restarts
and browser refreshes.

DEPLOYMENT NOTE: live generators are held in this process's memory, so
run a single worker (the default here). With multiple workers a session
would be replayed from disk on each worker that sees it, which works but
wastes CPU and risks interleaved writes to the same save file.
"""

import json
import random
import threading
import time
import uuid
from pathlib import Path

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from taipan.engine import Game

ROOT = Path(__file__).parent
SAVE_DIR = ROOT / "saves"
HIGHSCORE_FILE = SAVE_DIR / "highscores.json"
MAX_SESSIONS = 500
MAX_HIGHSCORES = 10

app = FastAPI(title="Taipan!")

_sessions: dict[str, dict] = {}
_registry_lock = threading.Lock()   # guards _sessions dict itself
_score_lock = threading.Lock()      # guards the high-score file


class StepRequest(BaseModel):
    session_id: str
    value: str | None = None


# ----------------------------------------------------------------------
# Save files

def _save_path(session_id: str) -> Path:
    # Session ids are generated by us as uuid hex; validate before using
    # them in a filesystem path.
    if not (len(session_id) == 32 and all(c in "0123456789abcdef"
                                          for c in session_id)):
        raise HTTPException(400, "Bad session id")
    return SAVE_DIR / f"{session_id}.json"


def _write_save(session_id: str, sess: dict):
    SAVE_DIR.mkdir(exist_ok=True)
    payload = {"seed": sess["seed"], "inputs": sess["inputs"],
               "scored": sess["scored"], "updated": time.time()}
    _save_path(session_id).write_text(json.dumps(payload),
                                      encoding="utf-8")


def _register(session_id: str, sess: dict):
    with _registry_lock:
        while len(_sessions) >= MAX_SESSIONS:
            _sessions.pop(next(iter(_sessions)))
        _sessions[session_id] = sess


def _restore(session_id: str) -> dict | None:
    """Rebuild a session from its save file by replaying the input log."""
    path = _save_path(session_id)
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    game = Game(seed=data["seed"])
    gen = game.run()
    event = next(gen)
    for value in data["inputs"]:
        try:
            event = gen.send(value)
        except StopIteration:
            break
    sess = {"gen": gen, "last": event, "seed": data["seed"],
            "inputs": data["inputs"], "scored": data.get("scored", False),
            "lock": threading.Lock()}
    _register(session_id, sess)
    return sess


def _get_session(session_id: str) -> dict:
    with _registry_lock:
        sess = _sessions.get(session_id)
    if sess is None:
        sess = _restore(session_id)
    if sess is None:
        raise HTTPException(404, "No such game")
    return sess


# ----------------------------------------------------------------------
# High scores

def _load_highscores() -> list:
    if HIGHSCORE_FILE.exists():
        return json.loads(HIGHSCORE_FILE.read_text(encoding="utf-8"))
    return []


def _record_highscore(event: dict):
    prompt = event.get("prompt") or {}
    state = event.get("state") or {}
    entry = {
        "firm": state.get("firm", "?"),
        "score": prompt.get("score", 0),
        "rating": prompt.get("rating", "?"),
        "date": f"{state.get('month', '?')} {state.get('year', '?')}",
        "when": time.strftime("%Y-%m-%d"),
    }
    with _score_lock:
        scores = _load_highscores()
        scores.append(entry)
        scores.sort(key=lambda s: s["score"], reverse=True)
        SAVE_DIR.mkdir(exist_ok=True)
        HIGHSCORE_FILE.write_text(
            json.dumps(scores[:MAX_HIGHSCORES], indent=1),
            encoding="utf-8")


# ----------------------------------------------------------------------
# API

@app.post("/api/new")
def new_game():
    seed = random.getrandbits(64)
    game = Game(seed=seed)
    gen = game.run()
    event = next(gen)
    session_id = uuid.uuid4().hex
    sess = {"gen": gen, "last": event, "seed": seed, "inputs": [],
            "scored": False, "lock": threading.Lock()}
    _register(session_id, sess)
    _write_save(session_id, sess)
    return {"session_id": session_id, "event": event}


@app.post("/api/step")
def step(req: StepRequest):
    sess = _get_session(req.session_id)
    with sess["lock"]:
        try:
            event = sess["gen"].send(req.value)
            sess["inputs"].append(req.value)
        except StopIteration:
            event = {**sess["last"], "messages": [], "done": True}
        sess["last"] = event
        if (event.get("done") and (event.get("prompt") or {}).get("kind")
                == "end" and not sess["scored"]):
            sess["scored"] = True
            _record_highscore(event)
        _write_save(req.session_id, sess)
    return {"event": event}


@app.get("/api/state/{session_id}")
def state(session_id: str):
    sess = _get_session(session_id)
    with sess["lock"]:
        # Re-deliver the last event, minus one-shot messages/fx that the
        # client already animated before the refresh.
        event = {**sess["last"], "messages": []}
    return {"event": event}


@app.get("/api/highscores")
def highscores():
    with _score_lock:
        return {"scores": _load_highscores()}


app.mount("/", StaticFiles(directory=ROOT / "static", html=True),
          name="static")


def main():
    uvicorn.run(app, host="127.0.0.1", port=8000)


if __name__ == "__main__":
    main()
