"""Taipan! web server: serves the retro UI and drives game sessions.

Persistence design: the engine is deterministic given its RNG seed, so a
game is fully described by (seed, list of inputs). Every step appends to
an on-disk event log in saves/; an unknown session id is restored by
replaying its log into a fresh generator. This survives server restarts
and browser refreshes.

DEPLOYMENT NOTE: live generators are held in this process's memory, so
run a single worker (the default here). With multiple workers a session
would be replayed from disk on each worker that sees it, which works but
wastes CPU and risks interleaved writes to the same save file.
"""

import hashlib
import json
import random
import threading
import time
import uuid
from datetime import date
from pathlib import Path

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from taipan.engine import ENGINE_VERSION, Game

ROOT = Path(__file__).parent
SAVE_DIR = ROOT / "saves"
HIGHSCORE_FILE = SAVE_DIR / "highscores.json"
DAILY_FILE = SAVE_DIR / "dailyscores.json"
MAX_SESSIONS = 500
MAX_HIGHSCORES = 10


def today() -> str:
    return date.today().isoformat()


def daily_seed(day: str) -> int:
    """Deterministic seed shared by every player on a given day."""
    return int(hashlib.sha256(f"taipan-daily-{day}".encode())
               .hexdigest()[:15], 16)

app = FastAPI(title="Taipan!")

_sessions: dict[str, dict] = {}
_registry_lock = threading.Lock()   # guards _sessions dict itself
_score_lock = threading.Lock()      # guards the high-score file


class NewRequest(BaseModel):
    daily: bool = False


class StepRequest(BaseModel):
    session_id: str
    value: str | None = None


# ----------------------------------------------------------------------
# Save files

def _save_path(session_id: str) -> Path:
    # Session ids are generated by us as uuid hex; validate before using
    # them in a filesystem path.
    if not (len(session_id) == 32 and all(c in "0123456789abcdef"
                                          for c in session_id)):
        raise HTTPException(400, "Bad session id")
    return SAVE_DIR / f"{session_id}.json"


def _write_save(session_id: str, sess: dict):
    SAVE_DIR.mkdir(exist_ok=True)
    payload = {"version": ENGINE_VERSION, "seed": sess["seed"],
               "inputs": sess["inputs"], "scored": sess["scored"],
               "daily": sess["daily"], "updated": time.time()}
    _save_path(session_id).write_text(json.dumps(payload),
                                      encoding="utf-8")


def _register(session_id: str, sess: dict):
    with _registry_lock:
        while len(_sessions) >= MAX_SESSIONS:
            _sessions.pop(next(iter(_sessions)))
        _sessions[session_id] = sess


def _restore(session_id: str) -> dict | None:
    """Rebuild a session from its save file by replaying the input log."""
    path = _save_path(session_id)
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("version") != ENGINE_VERSION:
        # The engine's prompt/RNG flow changed since this was saved;
        # replaying would produce a silently wrong game state.
        path.unlink(missing_ok=True)
        return None
    daily = data.get("daily")
    game = Game(seed=data["seed"],
                mode="classic" if daily else None, daily=daily)
    gen = game.run()
    event = next(gen)
    for value in data["inputs"]:
        try:
            event = gen.send(value)
        except StopIteration:
            break
    sess = {"gen": gen, "last": event, "seed": data["seed"],
            "inputs": data["inputs"], "scored": data.get("scored", False),
            "daily": daily, "lock": threading.Lock()}
    _register(session_id, sess)
    return sess


def _get_session(session_id: str) -> dict:
    with _registry_lock:
        sess = _sessions.get(session_id)
    if sess is None:
        sess = _restore(session_id)
    if sess is None:
        raise HTTPException(404, "No such game")
    return sess


# ----------------------------------------------------------------------
# High scores

def _load_json(path: Path, default):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return default


def _record_highscore(event: dict):
    prompt = event.get("prompt") or {}
    state = event.get("state") or {}
    daily = prompt.get("daily")
    entry = {
        "firm": state.get("firm", "?"),
        "score": prompt.get("score", 0),
        "rating": prompt.get("rating", "?"),
        "mode": prompt.get("mode", "classic"),
        "date": f"{state.get('month', '?')} {state.get('year', '?')}",
        "when": time.strftime("%Y-%m-%d"),
    }
    with _score_lock:
        SAVE_DIR.mkdir(exist_ok=True)
        scores = _load_json(HIGHSCORE_FILE, [])
        scores.append(entry)
        scores.sort(key=lambda s: s["score"], reverse=True)
        HIGHSCORE_FILE.write_text(
            json.dumps(scores[:MAX_HIGHSCORES], indent=1),
            encoding="utf-8")
        if daily:
            boards = _load_json(DAILY_FILE, {})
            board = boards.get(daily, [])
            board.append(entry)
            board.sort(key=lambda s: s["score"], reverse=True)
            boards[daily] = board[:MAX_HIGHSCORES]
            # Keep only the last two weeks of daily boards.
            for key in sorted(boards)[:-14]:
                del boards[key]
            DAILY_FILE.write_text(json.dumps(boards, indent=1),
                                  encoding="utf-8")


# ----------------------------------------------------------------------
# API

@app.post("/api/new")
def new_game(req: NewRequest):
    if req.daily:
        day = today()
        seed = daily_seed(day)
        game = Game(seed=seed, mode="classic", daily=day)
    else:
        day = None
        seed = random.getrandbits(64)
        game = Game(seed=seed)
    gen = game.run()
    event = next(gen)
    session_id = uuid.uuid4().hex
    sess = {"gen": gen, "last": event, "seed": seed, "inputs": [],
            "scored": False, "daily": day, "lock": threading.Lock()}
    _register(session_id, sess)
    _write_save(session_id, sess)
    return {"session_id": session_id, "event": event}


@app.post("/api/step")
def step(req: StepRequest):
    sess = _get_session(req.session_id)
    with sess["lock"]:
        try:
            event = sess["gen"].send(req.value)
            sess["inputs"].append(req.value)
        except StopIteration:
            event = {**sess["last"], "messages": [], "done": True}
        sess["last"] = event
        if (event.get("done") and (event.get("prompt") or {}).get("kind")
                == "end" and not sess["scored"]):
            sess["scored"] = True
            _record_highscore(event)
        _write_save(req.session_id, sess)
    return {"event": event}


@app.get("/api/state/{session_id}")
def state(session_id: str):
    sess = _get_session(session_id)
    with sess["lock"]:
        # Re-deliver the last event, minus one-shot messages/fx that the
        # client already animated before the refresh.
        event = {**sess["last"], "messages": []}
    return {"event": event}


@app.get("/api/highscores")
def highscores():
    day = today()
    with _score_lock:
        return {"scores": _load_json(HIGHSCORE_FILE, []),
                "daily_date": day,
                "daily_scores": _load_json(DAILY_FILE, {}).get(day, [])}


app.mount("/", StaticFiles(directory=ROOT / "static", html=True),
          name="static")


def main():
    uvicorn.run(app, host="127.0.0.1", port=8000)


if __name__ == "__main__":
    main()
